## Exercise: Clipping an array

Yes, NumPy has a `clip` ufunc already, but let's pretend it doesn't.  

Create a Numba vectorized ufunc that takes a vector `a`, a lower limit `amin` and an upper limit `amax`.  It should return the vector `a` with all values clipped such that $a_{min} < a < a_{max}$


In [4]:
from numba import vectorize
import numpy

In [22]:
@vectorize
def clip_matrix(a,amax,amin):
    
    assert amax > amin
    
    if a < amin:
        a = amin
    elif a > amax:
        a = amax
    return a

In [25]:
M = numpy.random.random((5,5))

M = M*10
print(M)

mn = 3
mx = 7

clip_matrix(M,mx,mn)

[[ 0.17778517  2.36475549  0.02082505  1.95497521  2.52375492]
 [ 4.71375963  9.12189915  1.34488985  8.83783545  5.34867519]
 [ 9.28062826  7.82926841  8.20544801  0.36984259  7.63630593]
 [ 0.93803823  7.70971214  3.68832786  5.80772556  9.22629522]
 [ 8.84952689  0.8211257   3.90769931  3.47682095  7.25471639]]


array([[ 3.        ,  3.        ,  3.        ,  3.        ,  3.        ],
       [ 4.71375963,  7.        ,  3.        ,  7.        ,  5.34867519],
       [ 7.        ,  7.        ,  7.        ,  3.        ,  7.        ],
       [ 3.        ,  7.        ,  3.68832786,  5.80772556,  7.        ],
       [ 7.        ,  3.        ,  3.90769931,  3.47682095,  7.        ]])

## Exercise: Create `logit` ufunc

Recall from above that this is a ufunc which performs this operation:

$$f(a) = \log \left(\frac{a}{1-a}\right)$$